### ISSUE TITLE
'::timespec_get' has not been declared

### ISSUE THREAD

**Issue by OneSkyknight** [conda-forge/root-feedstock#143]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>
'::timespec_get' has not been declared

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by chrisburr** [comment]
Hi @OneSkyknight, can you add some more details about what you’re doing and what exactly you see?

**Comment by eguiraud** [comment]
This is typically the symptom of having a mix of compiler/system libraries coming from conda-forge and default channels. Recreating the env from scratch specifying conda-forge and using strict channel priority should fix it, see also #139

**Comment by OneSkyknight** [comment]
Sorry to bother you. I have fixed this problem by "conda config --env --add channels conda-forge"
Thanks!



All the best！Baobiao Yue




---------------------------------
SYSU-School Physics
Cell:15622250382
***@***.***





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "conda-forge/root-feedstock"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月9日(星期四) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [conda-forge/root-feedstock] '::timespec_get' has not been declared (#143)





 
This is typically the symptom of having a mix of compiler/system libraries coming from conda-forge and default channels. Recreating the env from scratch specifying conda-forge and using strict channel priority should fix it, see also #139
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jingydz** [comment]
Has anyone tried using the command "conda config --env --add channels conda-forge" but it didn't solve the problem?

**Comment by jingydz** [comment]
Has anyone tried using the command "conda config --env --add channels conda-forge" but it didn't solve the problem?

**Comment by RyanbowZ** [comment]
> Has anyone tried using the command "conda config --env --add channels conda-forge" but it didn't solve the problem?

I executed this command and suddenly my conda environment get ruined, the basic conda operations will have problems, and pytorch no longer matches cuda version. So this command not only not solve this issue but introduce more complicated problems! Be cautious about using this!

**Comment by 13rac1** [comment]
Found myself here without a complete answer.

1. Edit your `$CONDA_PREFIX/.condarc` to strictly use `conda-forge`, note the order:
```
channels:
  - conda-forge
  - defaults
channel_priority: strict
```
2. Run `conda update --update-all` and update everything.

**References**

* https://github.com/conda-forge/root-feedstock/issues/139
* https://github.com/conda-forge/conda-forge.github.io/issues/1505
